Algoritmo "semnome"

Var

pais1 : caractere
c1 : real
m1 : real
pais2 : caractere
c2 : real
m2 : real
pais3 : caractere
c3 : real
m3 : real
pais4 : caractere
c4 : real
m4 : real
pais5 : caractere
c5 : real
m5 : real
pais6 : caractere
c6 : real
m6 : real
pais7 : caractere
c7 : real
m7 : real
pais8 : caractere
c8 : real
m8 : real
pais9 : caractere
c9 : real
m9 : real
pais10 : caractere
c10 : real
m10 : real
pais11 : caractere
c11 : real
m11 : real
pais12 : caractere
c12 : real
m12 : real
pais13 : caractere
c13 : real
m13 : real
pais14 : caractere
c14 : real
m14 : real
pais15 : caractere
c15 : real
m15 : real
media : real
mediana : real

Inicio

escreva("digite o nome do pais ")
  leia(pais1)
escreva("numero de casos ")
  leia(c1)
escreva("numero de mortes ")
  leia(m1)
escreva("digite nome do segundo pais ")
 leia(pais2)
escreva("numero de casos ")
 leia(c2)
escreva("numero de mortes ")
 leia(m2)
escreva("digite nome do terçeiro pais ")
 leia(pais3)
escreva("numero de casos ")
 leia(c3)
escreva("numero de mortes ")
 leia(m3)
escreva("digite nome do quarto pais ")
 leia(pais4)
escreva("numero de casos ")
 leia(c4)
escreva("numero de mortes ")
 leia(m4)
escreva("digite nome do quinto pais ")
 leia(pais5)
escreva("numero de casos ")
 leia(c5)
escreva("numero de mortes ")
 leia(m5)
escreva("digite nome do sexto pais ")
 leia(pais6)
escreva("numero de casos ")
 leia(c6)
escreva("numero de mortes ")
 leia(m6)
escreva("digite nome do setimo pais ")
 leia(pais7)
escreva("numero de casos ")
 leia(c7)
escreva("numero de mortes ")
 leia(m7)
escreva("digite nome do oitavo pais ")
 leia(pais8)
escreva("numero de casos ")
 leia(c8)
escreva("numero de mortes ")
 leia(m8)
escreva("digite nome do nono pais ")
 leia(pais9)
escreva("numero de casos ")
 leia(c9)
escreva("numero de mortes ")
 leia(m9)
escreva("digite nome do dezimo pais ")
 leia(pais10)
escreva("numero de casos ")
 leia(c10)
escreva("numero de mortes ")
 leia(m10)
escreva("digite nome do dezimo primeiro pais ")
 leia(pais11)
escreva("numero de casos ")
 leia(c11)
escreva("numero de mortes ")
 leia(m11)
escreva("digite nome do dezimo segundo pais ")
 leia(pais12)
escreva("numero de casos ")
 leia(c12)
escreva("numero do mortes ")
 leia(m12)
escreva("digite nome do dezimo terçeiro pais ")
 leia(pais13)
escreva("numero de casos ")
 leia(c13)
escreva("numero de mortes ")
 leia(m13)
escreva("digite nome do dezimo quarto pais ")
 leia(pais14)
escreva("numero de casos ")
 leia(c14)
escreva("numero de mortes ")
 leia(m14)
escreva("digite nome do dezimo quinto pais ")
 leia(pais15)
escreva("numero de casos ")
 leia(c15)
escreva("numero de mortes ")
 leia(m15)
        escreval(pais1 ," numero de casos ", c1 , " numero de mortes " , m1)
        escreval(pais2 ," numero de casos ", c2 , " numero de mortes " , m2)
        escreval(pais3 ," numero de casos ", c3 , " numero de mortes " , m3)
        escreval(pais4 ," numero de casos ", c4 , " numero de mortes " , m4)
        escreval(pais5 ," numero de casos ", c5 , " numero de mortes " , m5)
        escreval(pais6 ," numero de casos ", c6 , " numero de mortes " , m6)
        escreval(pais7 ," numero de casos ", c7 , " numero de mortes " , m7)
        escreval(pais8 ," numero de casos ", c8 , " numero de mortes " , m8)
        escreval(pais9 ," numero de casos ", c9 , " numero de mortes " , m9)
        escreval(pais10 ," numero de casos ", c10 , " numero de mortes " , m10)
        escreval(pais11 ," numero de casos ", c11 , " numero de mortes " , m11)
        escreval(pais12 ," numero de casos ", c12 , " numero de mortes " , m12)
        escreval(pais13 ," numero de casos ", c13 , " numero de mortes " , m13)
        escreval(pais14 ," numero de casos ", c14 , " numero de mortes " , m14)
        escreval(pais15 ," numero de casos ", c15 , " numero de mortes " , m15)
        
 media <- (c1 + c2 + c3 + c4 + c5 + c6 + c7 + c8 + c9 + c10 + c11 + c12 + c13 + c14 + c15)/15
 mediana <-(c7 + c8)/2
 
   escreval("a media é" , media )
   escreval("a media é" , mediana)
        
        
Fimalgoritmo